# Generated by Django 2.2.7 on 2019-12-02 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estilo_musical', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('instrumento_principal', models.TextField()),
                ('instrumentos_secundarios', models.TextField()),
                ('grupos_musicales', models.ManyToManyField(to='practica_06.GrupoMusical')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('distribuidora', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica_06.GrupoMusical')),
            ],
        ),
    ]
