# Generated by Django 2.2.7 on 2019-12-03 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practica_06', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='musico',
            name='instrumento_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='practica_06.Instrumentos'),
        ),
        migrations.RemoveField(
            model_name='musico',
            name='instrumentos_secundarios',
        ),
        migrations.AddField(
            model_name='musico',
            name='instrumentos_secundarios',
            field=models.ManyToManyField(blank=True, related_name='_musico_instrumentos_secundarios_+', to='practica_06.Instrumentos'),
        ),
    ]
