# Generated by Django 2.2.7 on 2019-12-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practica_06', '0002_auto_20191203_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musico',
            name='grupos_musicales',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='instrumento_principal',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='instrumentos_secundarios',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='GrupoMusical',
        ),
        migrations.DeleteModel(
            name='Instrumentos',
        ),
        migrations.DeleteModel(
            name='Musico',
        ),
    ]
