# Generated by Django 2.2.7 on 2019-12-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_06', '0004_album_grupomusical_instrumentos_musico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='instrumentos_secundarios',
            field=models.ManyToManyField(blank=True, related_name='secundarios', to='practica_06.Instrumentos'),
        ),
    ]
