# Generated by Django 2.2.7 on 2019-12-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_06', '0005_auto_20191203_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
