# Generated by Django 2.2.8 on 2019-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica_08', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musico',
            name='latitud',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='musico',
            name='longitud',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='musico',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
